version: "3.3"

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
<<<<<<< HEAD
    ports:
      - 3306:3306
    Expose:
      - 3306
=======
>>>>>>> a51b609ac5132375a70e524c71c75bd02bd57af9
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - drupal_network

  mydrupal:
    #build: .
    image: shrpanda0810/shraddhansu1
    container_name: drupal
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
    restart: always
    networks:
      - drupal_network
    volumes:
      - drupal-data:/var/www/html
<<<<<<< HEAD
=======
  
  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 60:60
    volumes:
      - drupal-data:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - external
  
>>>>>>> a51b609ac5132375a70e524c71c75bd02bd57af9

networks:
  drupal_network:
    driver: bridge

volumes:
  drupal-data:
  db-data: